# Generated by Django 3.2.5 on 2021-08-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0002_auto_20210828_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
