# Generated by Django 3.2.5 on 2021-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2),
        ),
    ]
