# Generated by Django 3.2.5 on 2021-08-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0003_auto_20210828_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
