# Generated by Django 3.2.5 on 2021-09-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0004_auto_20210907_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due', '-priority']},
        ),
    ]
