# Generated by Django 3.2.5 on 2021-08-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0005_alter_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
    ]
