# Generated by Django 3.2.5 on 2021-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0006_remove_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
