# Generated by Django 3.2.5 on 2021-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0007_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=20)),
            ],
        ),
    ]
