# Generated by Django 3.2.5 on 2021-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0009_alter_newuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='arcreactor.png', upload_to='images/'),
        ),
    ]
