# Generated by Django 3.2.5 on 2021-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0010_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='admin', max_length=20),
        ),
    ]
