# Generated by Django 3.2.5 on 2021-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0011_alter_newuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
