# Generated by Django 3.2.5 on 2021-09-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task0', '0012_task_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo',
        ),
    ]
